name: app
type: php:7.2
disk: 2048 # the needed mounts for the Dropbox daemon

mounts:
    Dropbox:
        source: local
        source_path: dropbox
    '/.dropbox':
        source: local
        source_path: 'dropbox-meta'

web:
    locations:
        '/':
          root: ''
          index:
            - index.php
    commands:
        start: |
            ~/.dropbox-dist/dropboxd >/dev/null 2>&1 &
             /usr/sbin/php-fpm7.2-zts # we do this by default for PHP7,
            # but you're overwriting the default web.commands.start so
            # you'll need to add it in manually.
            # Adjust according to your language and version.
            
hooks:
    build: |
        wget -nv "https://www.dropbox.com/download?plat=lnx.x86_64" -O archive.tar
        tar xzvf archive.tar && rm archive.tar
